version: "3.2"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - sky-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos-standalone
    environment:
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      MYSQL_SERVICE_DB_NAME: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    links:
      - mysql:mysql
    restart: always


  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  oap:
    image: apache/skywalking-oap-server:8.6.0-es7
    restart: always
    ports:
      - "11800"
      - "12800"
  oap-ui:
    image: apache/skywalking-ui:8.6.0
    restart: always
    ports: 
      - "10000:8080"
      
networks:
  sky-net:
volumes:
  sky-mysql:
